version: "3.8"
services: 
  node-server:
    build: 
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./src:/home/node/app/src
    command: npm start

  db:
    container_name: homeworks
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 4000:4000
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5