version: "3.8"
services: 
  node-server:
    build: 
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./src:/home/node/app/src
    command: npm start

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    env_file:
      - .env
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-data:
    driver: local