
volumes:
  postgres-db:

services:
  node-server:
    build: 
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./src:/home/node/app/src
      - /home/node/app/node_modules
    command: npm start

  db:
    container_name: homeworks
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "4000:5432" 
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

